// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHjLOh6t6iVHpDflzw6cu7jTP0UGQtPlg',
    appId: '1:856067300700:web:b2d46576d49dcaacf63599',
    messagingSenderId: '856067300700',
    projectId: 'flutter-chat-app-26773',
    authDomain: 'flutter-chat-app-26773.firebaseapp.com',
    storageBucket: 'flutter-chat-app-26773.firebasestorage.app',
    measurementId: 'G-CF7JLXFVD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbiqFL7T-flKGFZC7QmmYIFiyU_rNvb6c',
    appId: '1:856067300700:android:5e07adc8dcaddfbdf63599',
    messagingSenderId: '856067300700',
    projectId: 'flutter-chat-app-26773',
    storageBucket: 'flutter-chat-app-26773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCmbf3f2AXANC0q7VN52WnRybtcbAVrs',
    appId: '1:856067300700:ios:f94502526e687a15f63599',
    messagingSenderId: '856067300700',
    projectId: 'flutter-chat-app-26773',
    storageBucket: 'flutter-chat-app-26773.firebasestorage.app',
    iosClientId: '856067300700-7mls0nd3jfe2ml0fl57p4nhk8nfuc5ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtCmbf3f2AXANC0q7VN52WnRybtcbAVrs',
    appId: '1:856067300700:ios:f94502526e687a15f63599',
    messagingSenderId: '856067300700',
    projectId: 'flutter-chat-app-26773',
    storageBucket: 'flutter-chat-app-26773.firebasestorage.app',
    iosClientId: '856067300700-7mls0nd3jfe2ml0fl57p4nhk8nfuc5ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHjLOh6t6iVHpDflzw6cu7jTP0UGQtPlg',
    appId: '1:856067300700:web:5969bcdaa14b34e1f63599',
    messagingSenderId: '856067300700',
    projectId: 'flutter-chat-app-26773',
    authDomain: 'flutter-chat-app-26773.firebaseapp.com',
    storageBucket: 'flutter-chat-app-26773.firebasestorage.app',
    measurementId: 'G-SMVGRSJCB0',
  );
}
